name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.27'

    - name: Install PC/SC dev libraries
      if: runner.os == 'Linux'
      run: sudo apt-get update && sudo apt-get install -y pkg-config libpcsclite-dev

    - name: build windows release
      run: make build

    - name: build linux release
      run: make build-linux 
